name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request: 
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.9.0
      with:
        java-version: 17
        distribution: microsoft
    - name: Cache the maven packages to speed the build
      uses: actions/cache@v3.1.0-beta.3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
